"""Known-answer vectors transcribed from the reference implementation.

Each file names the reference `*.spec.ts` (or RFC) it came from. Nothing here
is generated by fxa-lite: a vector that agrees with our own output proves only
that we agree with ourselves, which is the one thing that cannot go wrong.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

DIRECTORY = Path(__file__).resolve().parent


def load(name: str) -> dict[str, Any]:
    return json.loads((DIRECTORY / f"{name}.json").read_text())


def cases(name: str, group: str) -> list[dict[str, Any]]:
    """One group of vectors, ready for `pytest.mark.parametrize`."""
    return load(name)[group]
